//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5485.
// 
namespace KPCTSDS.appserver {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://krishnapatnamport.nlr/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://172.168.1.30/rfid-web/RFID-Service.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/TestInsertDetails", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestInsertDetails(string empno, string name) {
            object[] results = this.Invoke("TestInsertDetails", new object[] {
                        empno,
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestInsertDetails(string empno, string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestInsertDetails", new object[] {
                        empno,
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTestInsertDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetReaderDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetReaderDetailsOracle(string ReaderIP) {
            object[] results = this.Invoke("GetReaderDetailsOracle", new object[] {
                        ReaderIP});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReaderDetailsOracle(string ReaderIP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReaderDetailsOracle", new object[] {
                        ReaderIP}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetReaderDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetMasterDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMasterDetailsOracle(string getDetails) {
            object[] results = this.Invoke("GetMasterDetailsOracle", new object[] {
                        getDetails});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMasterDetailsOracle(string getDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMasterDetailsOracle", new object[] {
                        getDetails}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetMasterDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/TagfreeOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int TagfreeOracle(string tagno) {
            object[] results = this.Invoke("TagfreeOracle", new object[] {
                        tagno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTagfreeOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TagfreeOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTagfreeOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/TruckfreeOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int TruckfreeOracle(string truckno) {
            object[] results = this.Invoke("TruckfreeOracle", new object[] {
                        truckno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTruckfreeOracle(string truckno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TruckfreeOracle", new object[] {
                        truckno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTruckfreeOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertRegDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertRegDetailsOracle(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime) {
            object[] results = this.Invoke("InsertRegDetailsOracle", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertRegDetailsOracle(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertRegDetailsOracle", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertRegDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertRegDetailsSyncOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertRegDetailsSyncOracle(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime) {
            object[] results = this.Invoke("InsertRegDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertRegDetailsSyncOracle(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertRegDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertRegDetailsSyncOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetTruckDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTruckDetailsOracle(string tagno) {
            object[] results = this.Invoke("GetTruckDetailsOracle", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTruckDetailsOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTruckDetailsOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTruckDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertUnRegDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUnRegDetailsOracle(string regid, string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime) {
            object[] results = this.Invoke("InsertUnRegDetailsOracle", new object[] {
                        regid,
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertUnRegDetailsOracle(string regid, string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertUnRegDetailsOracle", new object[] {
                        regid,
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertUnRegDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertUnRegDetailsSyncOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUnRegDetailsSyncOracle(string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime) {
            object[] results = this.Invoke("InsertUnRegDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertUnRegDetailsSyncOracle(string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertUnRegDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertUnRegDetailsSyncOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetDBTimeOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDBTimeOracle() {
            object[] results = this.Invoke("GetDBTimeOracle", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDBTimeOracle(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDBTimeOracle", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetDBTimeOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetTruckDetailsforYardOperationsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTruckDetailsforYardOperationsOracle(string tagno) {
            object[] results = this.Invoke("GetTruckDetailsforYardOperationsOracle", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTruckDetailsforYardOperationsOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTruckDetailsforYardOperationsOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTruckDetailsforYardOperationsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertYardOperationDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertYardOperationDetailsOracle(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime) {
            object[] results = this.Invoke("InsertYardOperationDetailsOracle", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertYardOperationDetailsOracle(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertYardOperationDetailsOracle", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertYardOperationDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertYardOperationDetailsSyncOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertYardOperationDetailsSyncOracle(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime) {
            object[] results = this.Invoke("InsertYardOperationDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertYardOperationDetailsSyncOracle(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertYardOperationDetailsSyncOracle", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertYardOperationDetailsSyncOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKPCTTruckDetailsOracle(string tagno, string usertype, string HHDlocation, string readerno, string user) {
            object[] results = this.Invoke("GetKPCTTruckDetailsOracle", new object[] {
                        tagno,
                        usertype,
                        HHDlocation,
                        readerno,
                        user});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckDetailsOracle(string tagno, string usertype, string HHDlocation, string readerno, string user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckDetailsOracle", new object[] {
                        tagno,
                        usertype,
                        HHDlocation,
                        readerno,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetKPCTTruckDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertKPCTOperationDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertKPCTOperationDetailsOracle(string tagno, string readerno, string saveoperation, string savetime, string user, string usertype, string HHDlocation, string Qty, string OPLOC, string CargoCondition, string WeatherCondition, string OpHandledBy, string OpHandledType, string TallySheetType, string ContainerNo) {
            object[] results = this.Invoke("InsertKPCTOperationDetailsOracle", new object[] {
                        tagno,
                        readerno,
                        saveoperation,
                        savetime,
                        user,
                        usertype,
                        HHDlocation,
                        Qty,
                        OPLOC,
                        CargoCondition,
                        WeatherCondition,
                        OpHandledBy,
                        OpHandledType,
                        TallySheetType,
                        ContainerNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertKPCTOperationDetailsOracle(
                    string tagno, 
                    string readerno, 
                    string saveoperation, 
                    string savetime, 
                    string user, 
                    string usertype, 
                    string HHDlocation, 
                    string Qty, 
                    string OPLOC, 
                    string CargoCondition, 
                    string WeatherCondition, 
                    string OpHandledBy, 
                    string OpHandledType, 
                    string TallySheetType, 
                    string ContainerNo, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("InsertKPCTOperationDetailsOracle", new object[] {
                        tagno,
                        readerno,
                        saveoperation,
                        savetime,
                        user,
                        usertype,
                        HHDlocation,
                        Qty,
                        OPLOC,
                        CargoCondition,
                        WeatherCondition,
                        OpHandledBy,
                        OpHandledType,
                        TallySheetType,
                        ContainerNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertKPCTOperationDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckTallySheetDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKPCTTruckTallySheetDetailsOracle(string tagno) {
            object[] results = this.Invoke("GetKPCTTruckTallySheetDetailsOracle", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckTallySheetDetailsOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckTallySheetDetailsOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetKPCTTruckTallySheetDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckTallySheetDetailsOracleNew", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKPCTTruckTallySheetDetailsOracleNew(string tagno) {
            object[] results = this.Invoke("GetKPCTTruckTallySheetDetailsOracleNew", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckTallySheetDetailsOracleNew(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckTallySheetDetailsOracleNew", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetKPCTTruckTallySheetDetailsOracleNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckTallySheetValidationDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKPCTTruckTallySheetValidationDetailsOracle(string tagno) {
            object[] results = this.Invoke("GetKPCTTruckTallySheetValidationDetailsOracle", new object[] {
                        tagno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckTallySheetValidationDetailsOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckTallySheetValidationDetailsOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetKPCTTruckTallySheetValidationDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckTallySheetLocationDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKPCTTruckTallySheetLocationDetailsOracle(string tagno) {
            object[] results = this.Invoke("GetKPCTTruckTallySheetLocationDetailsOracle", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckTallySheetLocationDetailsOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckTallySheetLocationDetailsOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetKPCTTruckTallySheetLocationDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertKPCTTruckTallySheetDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertKPCTTruckTallySheetDetailsOracle(string Val1, string Val2, string Val3, string Val4, string Val5, string Val6, string Val7, string Val8, string Val9, string tagno, string user, string savetime) {
            object[] results = this.Invoke("InsertKPCTTruckTallySheetDetailsOracle", new object[] {
                        Val1,
                        Val2,
                        Val3,
                        Val4,
                        Val5,
                        Val6,
                        Val7,
                        Val8,
                        Val9,
                        tagno,
                        user,
                        savetime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertKPCTTruckTallySheetDetailsOracle(string Val1, string Val2, string Val3, string Val4, string Val5, string Val6, string Val7, string Val8, string Val9, string tagno, string user, string savetime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertKPCTTruckTallySheetDetailsOracle", new object[] {
                        Val1,
                        Val2,
                        Val3,
                        Val4,
                        Val5,
                        Val6,
                        Val7,
                        Val8,
                        Val9,
                        tagno,
                        user,
                        savetime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertKPCTTruckTallySheetDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertKPCTTruckTallySheetDetailsOracleNew", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertKPCTTruckTallySheetDetailsOracleNew(string tagno, string width, string hight, string ctotal, string user, string savetime) {
            object[] results = this.Invoke("InsertKPCTTruckTallySheetDetailsOracleNew", new object[] {
                        tagno,
                        width,
                        hight,
                        ctotal,
                        user,
                        savetime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertKPCTTruckTallySheetDetailsOracleNew(string tagno, string width, string hight, string ctotal, string user, string savetime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertKPCTTruckTallySheetDetailsOracleNew", new object[] {
                        tagno,
                        width,
                        hight,
                        ctotal,
                        user,
                        savetime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertKPCTTruckTallySheetDetailsOracleNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetKPCTTruckReasonDetailsRequirementOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKPCTTruckReasonDetailsRequirementOracle(string tagno) {
            object[] results = this.Invoke("GetKPCTTruckReasonDetailsRequirementOracle", new object[] {
                        tagno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKPCTTruckReasonDetailsRequirementOracle(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKPCTTruckReasonDetailsRequirementOracle", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetKPCTTruckReasonDetailsRequirementOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertReasonDetailsOracle", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertReasonDetailsOracle(string tagno, string readerno, string saveoperation, string savetime, string user, string usertype, string HHDlocation, string Qty, string OPLOC, string reasonid, string reasondesc) {
            object[] results = this.Invoke("InsertReasonDetailsOracle", new object[] {
                        tagno,
                        readerno,
                        saveoperation,
                        savetime,
                        user,
                        usertype,
                        HHDlocation,
                        Qty,
                        OPLOC,
                        reasonid,
                        reasondesc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertReasonDetailsOracle(string tagno, string readerno, string saveoperation, string savetime, string user, string usertype, string HHDlocation, string Qty, string OPLOC, string reasonid, string reasondesc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertReasonDetailsOracle", new object[] {
                        tagno,
                        readerno,
                        saveoperation,
                        savetime,
                        user,
                        usertype,
                        HHDlocation,
                        Qty,
                        OPLOC,
                        reasonid,
                        reasondesc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertReasonDetailsOracle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetLocationMasterDetailsCFSSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLocationMasterDetailsCFSSQL(string getDetails) {
            object[] results = this.Invoke("GetLocationMasterDetailsCFSSQL", new object[] {
                        getDetails});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLocationMasterDetailsCFSSQL(string getDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLocationMasterDetailsCFSSQL", new object[] {
                        getDetails}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetLocationMasterDetailsCFSSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetLocationDetailsCFSSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLocationDetailsCFSSQL(string LocationId) {
            object[] results = this.Invoke("GetLocationDetailsCFSSQL", new object[] {
                        LocationId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLocationDetailsCFSSQL(string LocationId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLocationDetailsCFSSQL", new object[] {
                        LocationId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetLocationDetailsCFSSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetDBTimeSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDBTimeSQL() {
            object[] results = this.Invoke("GetDBTimeSQL", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDBTimeSQL(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDBTimeSQL", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetDBTimeSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetReaderDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetReaderDetailsSQL(string ReaderIP) {
            object[] results = this.Invoke("GetReaderDetailsSQL", new object[] {
                        ReaderIP});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReaderDetailsSQL(string ReaderIP, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReaderDetailsSQL", new object[] {
                        ReaderIP}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetReaderDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetMasterDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMasterDetailsSQL(string getDetails) {
            object[] results = this.Invoke("GetMasterDetailsSQL", new object[] {
                        getDetails});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMasterDetailsSQL(string getDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMasterDetailsSQL", new object[] {
                        getDetails}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetMasterDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/TagfreeSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int TagfreeSQL(string tagno) {
            object[] results = this.Invoke("TagfreeSQL", new object[] {
                        tagno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTagfreeSQL(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TagfreeSQL", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTagfreeSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/TruckfreeSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int TruckfreeSQL(string truckno) {
            object[] results = this.Invoke("TruckfreeSQL", new object[] {
                        truckno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTruckfreeSQL(string truckno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TruckfreeSQL", new object[] {
                        truckno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTruckfreeSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertRegDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertRegDetailsSQL(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime) {
            object[] results = this.Invoke("InsertRegDetailsSQL", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertRegDetailsSQL(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertRegDetailsSQL", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertRegDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertRegDetailsSyncSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertRegDetailsSyncSQL(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime) {
            object[] results = this.Invoke("InsertRegDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertRegDetailsSyncSQL(string tagno, string truckno, string optype, string readerno, string readerip, string user, string trucktype, string remarks, string regtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertRegDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        optype,
                        readerno,
                        readerip,
                        user,
                        trucktype,
                        remarks,
                        regtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertRegDetailsSyncSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetTruckDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTruckDetailsSQL(string tagno) {
            object[] results = this.Invoke("GetTruckDetailsSQL", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTruckDetailsSQL(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTruckDetailsSQL", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTruckDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertUnRegDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUnRegDetailsSQL(string regid, string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime) {
            object[] results = this.Invoke("InsertUnRegDetailsSQL", new object[] {
                        regid,
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertUnRegDetailsSQL(string regid, string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertUnRegDetailsSQL", new object[] {
                        regid,
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertUnRegDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertUnRegDetailsSyncSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertUnRegDetailsSyncSQL(string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime) {
            object[] results = this.Invoke("InsertUnRegDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertUnRegDetailsSyncSQL(string tagno, string truckno, string trucktype, string readerno, string readerip, string user, string unregtime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertUnRegDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        trucktype,
                        readerno,
                        readerip,
                        user,
                        unregtime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertUnRegDetailsSyncSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/GetTruckDetailsforYardOperationsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTruckDetailsforYardOperationsSQL(string tagno) {
            object[] results = this.Invoke("GetTruckDetailsforYardOperationsSQL", new object[] {
                        tagno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTruckDetailsforYardOperationsSQL(string tagno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTruckDetailsforYardOperationsSQL", new object[] {
                        tagno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTruckDetailsforYardOperationsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertYardOperationDetailsSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertYardOperationDetailsSQL(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime) {
            object[] results = this.Invoke("InsertYardOperationDetailsSQL", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertYardOperationDetailsSQL(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertYardOperationDetailsSQL", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertYardOperationDetailsSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://krishnapatnamport.nlr/InsertYardOperationDetailsSyncSQL", RequestNamespace="http://krishnapatnamport.nlr/", ResponseNamespace="http://krishnapatnamport.nlr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertYardOperationDetailsSyncSQL(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime) {
            object[] results = this.Invoke("InsertYardOperationDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertYardOperationDetailsSyncSQL(string tagno, string truckno, string loaderid, string readerno, string readerip, string user, string yardoptime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertYardOperationDetailsSyncSQL", new object[] {
                        tagno,
                        truckno,
                        loaderid,
                        readerno,
                        readerip,
                        user,
                        yardoptime}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInsertYardOperationDetailsSyncSQL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
